name: Update Showtimes

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 4 AM UTC daily
  workflow_dispatch:      # Allows manual triggers

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: npm run update-showtimes
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          # ... other env vars 